### ISSUE TITLE
无法查看 登录二维码

### ISSUE THREAD

**Issue by Feb17** [louisyoungx/JD-SHOPPER#1]
环境：
Platform: Oracle cloud 
OS: CentOS Linux release 7.9.2009 (Core)
Kernel: 3.10.0-1160.45.1.el7.x86_64

首先是提示EOG 没有安装，安装了之后提示 **(eog:18993): Gtk-WARNING **: 04:18:27.984: cannot open display:**

===== 注意 =====
使用前请按要求填写config.ini中的信息

功能列表：
 1.自动加购物车，缺货等待上架自动下单
 2.自动定时加购物车下单（普通商品，非秒杀抢购）

请选择:1
[2021-11-24 04:18:26] (spider.new_func): <INFO> waitForSell 需登陆后调用，开始扫码登陆
[2021-11-24 04:18:27] (login._get_qrcode): <INFO> 二维码获取成功，请打开京东APP扫描

**(eog:18993): Gtk-WARNING **: 04:18:27.984: cannot open display:**
[2021-11-24 04:18:28] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 04:18:30] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 04:18:32] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 04:18:35] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 04:18:37] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
[2021-11-24 04:18:39] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码

**Comment by louisyoungx** [comment]
目测是系统权限的问题啊，你手动打开Static/img/qr_code.png也能扫

**Comment by Feb17** [comment]
我想问下，这个eog 是不是只有装了图形界面才能使用啊……

> 目测是系统权限的问题啊，你手动打开Static/img/qr_code.png也能扫

**Comment by louisyoungx** [comment]
> 我想问下，这个eog 是不是只有装了图形界面才能使用啊……
> 
> > 目测是系统权限的问题啊，你手动打开Static/img/qr_code.png也能扫
> 
> 

并不是，事实上这是我第一次看到这个报错。能用sudo启动并贴一下全部报错信息吗。

**Comment by louisyoungx** [comment]
查了原因，是 **系统权限** 问题

> Xserver默认情况下不允许别的用户的图形程序的图形显示在当前屏幕上

可以用sudo启动项目
或者在项目上层文件夹使用如下命令
```shell
sudo chmod -R 777 JD-SHOPPER/
```

**Comment by Feb17** [comment]
谷歌了下，通过https://www.jianshu.com/p/ac5159626ce9 这个方法开启了X11 forwarding.  依旧报错。 

改了777权限也是一样。

> [root@instance-20211027-1005 ~]# ll JD-SHOPPER/
total 60
drwxrwxrwx. 3 root root   104 Nov 24 04:13 Config
drwxrwxrwx. 3 root root   143 Nov 24 04:13 Core
drwxrwxrwx. 3 root root    55 Nov 24 02:57 Docs
drwxrwxrwx. 2 root root    67 Nov 24 02:57 GUI
-rwxrwxrwx. 1 root root 35149 Nov 24 02:57 LICENSE
drwxrwxrwx. 4 root root    78 Nov 24 04:13 Logger
-rwxrwxrwx. 1 root root   788 Nov 24 02:57 main.py
drwxrwxrwx. 3 root root    62 Nov 24 04:13 Message
-rwxrwxrwx. 1 root root  7083 Nov 24 02:57 README.md
-rwxrwxrwx. 1 root root    39 Nov 24 02:57 requirements.txt
-rwxrwxrwx. 1 root root  3652 Nov 24 05:11 root@feb17.gtmdgcd.win
-rwxrwxrwx. 1 root root  1601 Nov 24 02:57 runserver.py
drwxrwxrwx. 2 root root    45 Nov 24 02:57 Scheduler
drwxrwxrwx. 2 root root   102 Nov 24 02:57 Server
drwxrwxrwx. 5 root root    91 Nov 24 02:57 Static
drwxrwxrwx. 3 root root   100 Nov 24 02:57 TEST

Log: 
> [root@instance-20211027-1005 JD-SHOPPER]# sudo python3 main.py
>===== 注意 =====
>使用前请按要求填写config.ini中的信息

>功能列表：
 >1.自动加购物车，缺货等待上架自动下单
 >2.自动定时加购物车下单（普通商品，非秒杀抢购）

>请选择:1
>[2021-11-24 06:02:15] (spider.new_func): <INFO> waitForSell 需登陆后调用，开始扫码登陆
>[2021-11-24 06:02:16] (login._get_qrcode): <INFO> 二维码获取成功，请打开京东APP扫描
**>**MoTTY X11 proxy: Unsupported authorisation protocol**
>**(eog:20008): Gtk-WARNING **: 06:02:16.865: cannot open display: localhost:10.0****
>[2021-11-24 06:02:17] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
>[2021-11-24 06:02:19] (login._get_qrcode_ticket): <INFO> Code: 201, Message: 二维码未扫描，请扫描二维码
>^CTraceback (most recent call last):
>  File "main.py", line 20, in <module>
>   waiter.waitForSell()
> File "/root/JD-SHOPPER/Core/spider.py", line 90, in new_func
>    self.login_by_qrcode()
>  File "/root/JD-SHOPPER/Core/spider.py", line 73, in login_by_qrcode
>    self.qrlogin.login_by_qrcode()
>  File "/root/JD-SHOPPER/Core/login.py", line 245, in login_by_qrcode
>    time.sleep(2)
>KeyboardInterrupt

**Comment by louisyoungx** [comment]
抱歉，对这样Linux发行版的特定系统问题我没有解决思路，这和本项目无关。
我在自己的centos7服务器，Ubuntu20服务器，macos，windows上都测试过了，没有发现这个问题。
你可以手动打开Static/img/qr_xode.png进行扫码登录，或者换一个操作系统运行。
运行web版本可以无视这个报错。
如果没有其他问题本issue将很快关闭。

**Comment by louisyoungx** [comment]
如果有发现其他问题，可以提交新的issue😊

如果可以通过修改代码来提高兼容性，可以提交pr，测试过后会很快合并，谢谢支持😊
