### ISSUE TITLE
时间不对，延迟八个小时（时区错误）

### ISSUE THREAD

**Issue by Jerryhuan** [louisyoungx/JD-SHOPPER#10]
填单时选择的时间和运行后显示的设定时间有出入，运行后显示的设定时间比选择的时间延迟八个小时。
麻烦作者确认下这个问题

**Comment by louisyoungx** [comment]
你用的是web页面和客户端吗
应该是时区没有设成+8时区，后续我会修改

**Comment by louisyoungx** [comment]
最新版本已修复
