### ISSUE TITLE
频繁刷库存接口，会被拉黑IP（并非账号）

### ISSUE THREAD

**Issue by q474818917** [louisyoungx/JD-SHOPPER#14]
这种情况如何解决
jQuery3818267({"100007090880":{"StockState":33,"area":{"townName":"","provinceName":"北京","cityName":"朝阳区","success":true,"countyName":"三环以内"},"realSkuId":100007090880,"code":1,"err":true,"PopType":0,"ArrivalDate":null,"IsPurchase":false,"StockStateName":"有货","rn":-1}})

**Comment by louisyoungx** [comment]
配置里面`area`, `eid`, `fp`都填对了吗

**Comment by q474818917** [comment]
> 配置里面`area`, `eid`, `fp`都填对了吗

都是对的，用接口调也是同样的问题，好像跟ip有关

**Comment by louisyoungx** [comment]
是的，如果你ip已经被拉黑可以用手机热点换个ip（如果没有ip代理池或vpn的话）

**Comment by q474818917** [comment]
> 是的，如果你ip已经被拉黑可以用手机热点换个ip（如果没有ip代理池或vpn的话）
我可能减少了timeout参数值，这个值大致需要设置多少，才不会被判黑

**Comment by louisyoungx** [comment]
这个timeout风控不是固定的，看你使用时长，短期使用可以频率略高，长期使用（24小时以上）必须低频（1分钟一次稳妥）

**Comment by q474818917** [comment]
多谢
