### ISSUE TITLE
login qr_code.png does not exist.

### ISSUE THREAD

**Issue by haohongwei** [louisyoungx/JD-SHOPPER#15]
[2022-02-24 15:30:53] (spider.new_func): <INFO> waitForSell 需登陆后调用，开始扫码登陆
[2022-02-24 15:30:53] (login._get_qrcode): <INFO> 二维码获取成功，请打开京东APP扫描
The file /Users/xxx/Desktop/JD-SHOPPER/qr_code.png does not exist.

The path of the qrcode image is not correct except for Windows.

```
def open_image(image_file):
    if os.name == "nt":
        os.system('start ' + config.path() + '/Static/img/'+ image_file)  # for Windows
    else:
        if os.uname()[0] == "Linux":
            if "deepin" in os.uname()[2]:
                os.system("deepin-image-viewer " + image_file)  # for deepin
            else:
                os.system("eog " + image_file)  # for Linux
        else:
            os.system("open " + image_file)  # for Mac
```

**Comment by louisyoungx** [comment]
我明天看看源码，我mac上打开没问题

**Comment by louisyoungx** [comment]
确定一下是否有权限，如果没有正常跳出可以手动打开 `JD-SHOPPER/Static/img/` 目录下的 `qr_code.png` 文件扫码登陆
