### ISSUE TITLE
用命令行启动不显示登录二维码.

### ISSUE THREAD

**Issue by sincere518** [louisyoungx/JD-SHOPPER#20]
用命令行启动不显示登录二维码.没有生成“qr_code.png”文件!

**Comment by louisyoungx** [comment]
确定一下是否有权限，如果没有正常跳出可以手动打开 `JD-SHOPPER/Static/img/` 目录下的 `qr_code.png` 文件扫码登陆

**Comment by sincere518** [comment]
已解决,谢谢!
