### ISSUE TITLE
 安装依赖报错，无法安装依赖（Python未正确安装，环境变量错误）

### ISSUE THREAD

**Issue by AllenWlei** [louisyoungx/JD-SHOPPER#26]
![image](https://user-images.githubusercontent.com/100189966/156101702-b193cb24-bc54-4c65-9499-62a7c8ac2065.png)

**Comment by AllenWlei** [comment]
> 没装
pip install -r requirements.txt
我执行过了呀  还是不行

**Comment by AllenWlei** [comment]
> 依赖没装

pip install -r requirements.txt  执行是报错的  
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install requests lxml bs4
都报错

**Comment by AllenWlei** [comment]
> 



> > > 依赖没装
> > 
> > 
> > pip install -r requirements.txt 执行是报错的 pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ pip install requests lxml bs4 都报错
> 
> 终极解决办法
> 
> ```python
> python -m pip install requests lxml bs4
> ```

依然报错

![image](https://user-images.githubusercontent.com/100189966/156304933-cf5aace3-9fe3-4b91-91df-ee81b581f1a0.png)

**Comment by louisyoungx** [comment]
> > > > 依赖没装
> > > 
> > > 
> > > pip install -r requirements.txt 执行是报错的 pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ pip install requests lxml bs4 都报错
> > 
> > 
> > 终极解决办法
> > ```python
> > python -m pip install requests lxml bs4
> > ```
> 
> 依然报错
> 
> ![image](https://user-images.githubusercontent.com/100189966/156304933-cf5aace3-9fe3-4b91-91df-ee81b581f1a0.png)

这就是python没有正确安装，把这个卸载了去官网装最新版的

> 安装的时候要勾选添加到环境变量（不要忘）

**Comment by AllenWlei** [comment]
> > > > > 依赖没装
> > > > 
> > > > 
> > > > pip install -r requirements.txt 执行是报错的 pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ pip install requests lxml bs4 都报错
> > > 
> > > 
> > > 终极解决办法
> > > ```python
> > > python -m pip install requests lxml bs4
> > > ```
> > 
> > 
> > 依然报错
> > ![image](https://user-images.githubusercontent.com/100189966/156304933-cf5aace3-9fe3-4b91-91df-ee81b581f1a0.png)
> 
> 这就是python没有正确安装，把这个卸载了去官网装最新版的
> 
> > 安装的时候要勾选添加到环境变量（不要忘）

![image](https://user-images.githubusercontent.com/100189966/156307319-9acd9010-1ed2-45ad-8a9b-934d2c394bdc.png)
这样有问题么？ 我记得我勾选了的

**Comment by louisyoungx** [comment]
要不你到应用商店下载 `windows terminal` 再试试
