### ISSUE TITLE
win10 打开应用程序无反应

### ISSUE THREAD

**Issue by XiaoHb233** [louisyoungx/jd-shopper#3]
win10 企业版 打开应用程序无反应

**Comment by louisyoungx** [comment]
如果打开的是客户端的话，那可能只有win11能用（是在win11上打包的，bug非常多）
如果是web版或命令行版本，可以尝试用这条命令启动（Python环境配置问题导致）
```shell
python main.py        # 命令行版
python run server    # web版
```

**Comment by louisyoungx** [comment]
最新版 [jd-shopper.exe](https://github.com/louisyoungx/jd-shopper/releases/tag/v1.2.1) 已经修复了所有问题
