### ISSUE TITLE
频繁刷新导致请求被拒绝怎么办？（降低请求频率或换ip）

### ISSUE THREAD

**Issue by aheadlcx** [louisyoungx/JD-SHOPPER#32]
(spider.get_checkout_page_detail): <ERROR> 刷新太频繁了 url: http://trade.jd.com/shopping/order/getOrderInfo.action

咨询一下，这是什么意思了

**Comment by louisyoungx** [comment]
你用网页打开淘宝或京东，然后疯狂刷新，你就会看到这个页面真正的样子

**Comment by louisyoungx** [comment]
没有别的问题我关掉这个issue了

**Comment by aheadlcx** [comment]
@louisyoungx 感谢回复。看了下日志，第一次请求就返回这个了，这个可能是账号或者ip污染了么？

**Comment by louisyoungx** [comment]
和账户没关系，如果是这样的话，应该是ip问题。
可以切换到手机热点，或者通过代理换个ip

**Comment by aheadlcx** [comment]
这个，现在还能抢茅台么

**Comment by aheadlcx** [comment]
噢，这个，现在还能抢茅台么

**Comment by louisyoungx** [comment]
想拿这个赚钱就免了吧......我害怕
