### ISSUE TITLE
通过Windows运行程序如何停止？（最新版点击关闭即可）

### ISSUE THREAD

**Issue by uxfion** [louisyoungx/jd-shopper#34]
请问一下通过Windows运行程序如何手动STOP？

**Comment by louisyoungx** [comment]
根据广大用户的使用经验，目前只能通过打开任务管理器，杀掉进程······

**Comment by louisyoungx** [comment]
下次更新会修复这个功能

**Comment by louisyoungx** [comment]
下次更新客户端会修复这个功能

**Comment by louisyoungx** [comment]
没有其他问题本issue将关闭

**Comment by louisyoungx** [comment]
最新版的客户端已经能直接关闭了

**Comment by louisyoungx** [comment]
最新版 [jd-shopper.exe](https://github.com/louisyoungx/jd-shopper/releases/tag/v1.2.1) 已经修复了所有问题
