### ISSUE TITLE
web模式下获取二维码失败

### ISSUE THREAD

**Issue by dkl78167816** [louisyoungx/JD-SHOPPER#35]
## 问题描述

看起来前端传的请求有问题？`id={this.qrID}`，此外，static/img目录下也没有二维码图片

![image](https://user-images.githubusercontent.com/32244400/157368364-34042cbf-cbc0-49da-bd58-2d6c1dbbebee.png)

部署在debian服务器上，通过修改config，远程访问web网址

## 前端请求

`get img/qr_code.png?id={this.qrID} 200 OK`

## 后端log
```bash
Traceback (most recent call last):
  File "miniconda3/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "workspace/python/JD-SHOPPER/Server/handler.py", line 38, in do_GET
    self.file(url)
  File "workspace/python/JD-SHOPPER/Server/handler.py", line 120, in file
    file_page_file = open(file_path, 'r', encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by louisyoungx** [comment]
## 没有权限
权限问题导致图片没有正确生成，用root运行主程序即可。
```
# 使用sudo
sudo python3 main.py
# 或者切换到root
su root
# 或者给JD-SHOPPER目录权限
chmod -R 777 JD-SHOPPER
# 或者修改JD-SHOPEER所属用户
chown -R 用户名:你的组 JD-SHOPPER
```
> 前端加这个id是为了不让浏览器缓存图片，不影响请求

## 另外一个你即将遇到的问题
京东的二维码 只能用**本局域网内的手机**扫码解锁
手机和服务器不在同一个局域网内扫码是不被京东允许的。
服务器不在本地，也可以通过以下步骤运行：
> 1. 先在本地运行项目，扫码后关闭项目
> 2. 复制cookies/目录下你的cookie到你的服务器项目的cookies目录下
> 3. 使用root权限运行服务器下项目

**Comment by dkl78167816** [comment]
> ## 没有权限
> 权限问题导致图片没有正确生成，用root运行主程序即可。
> 
> ```
> # 使用sudo
> sudo python3 main.py
> # 或者切换到root
> su root
> # 或者给JD-SHOPPER目录权限
> chmod -R 777 JD-SHOPPER
> # 或者修改JD-SHOPEER所属用户
> chown -R 用户名:你的组 JD-SHOPPER
> ```
> 
> > 前端加这个id是为了不让浏览器缓存图片，不影响请求
> 
> ## 另外一个你即将遇到的问题
> 京东的二维码 只能用**本局域网内的手机**扫码解锁 手机和服务器不在同一个局域网内扫码是不被京东允许的。 服务器不在本地，也可以通过以下步骤运行：
> 
> > 1. 先在本地运行项目，扫码后关闭项目
> > 2. 复制cookies/目录下你的cookie到你的服务器项目的cookies目录下
> > 3. 使用root权限运行服务器下项目

**Comment by dkl78167816** [comment]
> ## 没有权限
> 权限问题导致图片没有正确生成，用root运行主程序即可。
> 
> ```
> # 使用sudo
> sudo python3 main.py
> # 或者切换到root
> su root
> # 或者给JD-SHOPPER目录权限
> chmod -R 777 JD-SHOPPER
> # 或者修改JD-SHOPEER所属用户
> chown -R 用户名:你的组 JD-SHOPPER
> ```
> 
> > 前端加这个id是为了不让浏览器缓存图片，不影响请求
> 
> ## 另外一个你即将遇到的问题
> 京东的二维码 只能用**本局域网内的手机**扫码解锁 手机和服务器不在同一个局域网内扫码是不被京东允许的。 服务器不在本地，也可以通过以下步骤运行：
> 
> > 1. 先在本地运行项目，扫码后关闭项目
> > 2. 复制cookies/目录下你的cookie到你的服务器项目的cookies目录下
> > 3. 使用root权限运行服务器下项目

检查了一下，所使用的命令、目录都没有权限问题，使用`sudo python runserver.py`也是上述错误。

而在尝试执行`python main.py`后，本地生成了二维码，进而可以在`python runserver.py`的web端获取二维码

感谢作者大大详细的解答
