### ISSUE TITLE
地址对应ID怎么填？

### ISSUE THREAD

**Issue by SmallMousePP** [louisyoungx/JD-SHOPPER#36]
https://github.com/louisyoungx/JD-SHOPPER/blob/master/area_id

页面404

**Comment by NERVEbing** [comment]
尽量仔细看完文档再提issues
https://github.com/louisyoungx/JD-SHOPPER/tree/master/TEST/area_id

> ### *web*界面 - 使用教程
> ...
> 2. 到 */TEST/area_id/* 目录下查询你所在地的地区标识ID
> ...
