### ISSUE TITLE
eid 为空

### ISSUE THREAD

**Issue by Marvll** [louisyoungx/JD-SHOPPER#37]
![image](https://user-images.githubusercontent.com/88202244/158046384-eb93c09d-64c6-4119-8c3b-f282d4921126.png)
![image](https://user-images.githubusercontent.com/88202244/158046427-6134a6e4-5d45-49a4-94fb-6ee11a73372c.png)

**Comment by louisyoungx** [comment]
登录了吗

**Comment by Marvll** [comment]
> 登录了吗

登录了 但只有fp

**Comment by louisyoungx** [comment]
尝试打开 `TEST`  目录下的 `get_eid_fp.html` 文件获取eid和fp
如果还是没有就用手机热点获取新的ip

**Comment by Marvll** [comment]
> 尝试打开 `TEST` 目录下的 `get_eid_fp.html` 文件获取eid和fp 如果还是没有就用手机热点获取新的ip

图一就是html获取的，改密码换国内外ip都没eid 我裂开了

**Comment by louisyoungx** [comment]
要不你随便编一个试试，要是能启动就算了吧
