### ISSUE TITLE
jd-shopper.exe，下载了压缩包，在win10上用不了

### ISSUE THREAD

**Issue by septwolf1** [louisyoungx/jd-shopper#39]
jd-shopper.exe，，后台运行了一下就没有了

**Comment by louisyoungx** [comment]
这就对了🤪已经一年没更新了🤣

本月我会更新一个新版客户端

**Comment by louisyoungx** [comment]
最新版 [jd-shopper.exe](https://github.com/louisyoungx/jd-shopper/releases/tag/v1.2.1) 已经修复了所有问题
