### ISSUE TITLE
预约商品的抢购模式能用吗？（暂时不能用）

### ISSUE THREAD

**Issue by rickyi22** [louisyoungx/JD-SHOPPER#4]

**Comment by louisyoungx** [comment]
抢购秒杀的商品是没法用的，和普通商品接口完全不一样

**Comment by louisyoungx** [comment]
如果有人对抢购秒杀模式感兴趣可以看V0.0.1之前的版本，
在订单结算页面有个跳转接口有点问题，
如果通过抓包抓到新接口欢迎在本项目提交新的PR
