### ISSUE TITLE
全部勾选失效

### ISSUE THREAD

**Issue by lxPazz** [louisyoungx/jd-shopper#42]
https://cart.jd.com/selectAllItem.action  勾选不了了

**Comment by louisyoungx** [comment]
能否详细描述所遇到的问题

**Comment by lxPazz** [comment]
select_all_cart_item  这个函数执行完，购物车里没反应，并没有全部勾选上

**Comment by louisyoungx** [comment]
我下个版本会把这个冗余函数删掉，如果这个api对你有用请自行抓包
