### ISSUE TITLE
windows开箱即用exe程序只支持Win11

### ISSUE THREAD

**Issue by cxs13991120** [louisyoungx/jd-shopper#5]
windows开箱即用exe程序打开没反应，程序显示不出来

**Comment by louisyoungx** [comment]
很多人反馈了这个问题，最后发现是只能在win11上用
因为这个程序是在win11上打包的

**Comment by louisyoungx** [comment]
所以win10，用web或者命令行版本吧
以后也不会对win10做适配

**Comment by louisyoungx** [comment]
最新版 [jd-shopper.exe](https://github.com/louisyoungx/jd-shopper/releases/tag/v1.2.1) 已经修复了所有问题
