### ISSUE TITLE
有货商品一直提示等待上架

### ISSUE THREAD

**Issue by chengzhijun0706** [louisyoungx/JD-SHOPPER#6]
![image](https://user-images.githubusercontent.com/13751034/147444567-98482519-30dd-4a0e-bf75-c5067e2a6439.png)
我填了一个直接可以购买的链接，但是一直提示等待上架，是为什么呢

**Comment by louisyoungx** [comment]
下个星期我会修复这个问题

**Comment by chengzhijun0706** [comment]
@louisyoungx 多谢大佬，谢谢啦

**Comment by laodiaoyadashu** [comment]
> 下个星期我会修复这个问题
京东查询库存的api用默认的'user-agent'访问会出错。更换'user-agent'就可以了

**Comment by laodiaoyadashu** [comment]
> ![image](https://user-images.githubusercontent.com/13751034/147444567-98482519-30dd-4a0e-bf75-c5067e2a6439.png) 我填了一个直接可以购买的链接，但是一直提示等待上架，是为什么呢

源代码里/Core/spider.py，第251行
```
#'User-Agent': self.user_agent,`
from Core.util import get_random_useragent
'User-Agent': get_random_useragent(),

**Comment by louisyoungx** [comment]
> > ![image](https://user-images.githubusercontent.com/13751034/147444567-98482519-30dd-4a0e-bf75-c5067e2a6439.png) 我填了一个直接可以购买的链接，但是一直提示等待上架，是为什么呢
> 
> 源代码里/Core/spider.py，第251行
> 
> ```
> #'User-Agent': self.user_agent,`
> from Core.util import get_random_useragent
> 'User-Agent': get_random_useragent(),
> ```

谢谢！你能提交个Pull Request吗，成为JD-SHOPPER的贡献者

**Comment by 8030046** [comment]
新下的版本，一开始没有，第二天还是有这问题

<img width="560" alt="image" src="https://user-images.githubusercontent.com/34773469/153139770-f9f397c9-c2e0-4679-a3fd-c1d76084f64e.png">
