### ISSUE TITLE
win11 打不开，软件可以打开 但是打不开里面的页面

### ISSUE THREAD

**Issue by donqee** [louisyoungx/jd-shopper#9]

**Comment by louisyoungx** [comment]
软件问题很多。浏览器打开 [http://localhost:12021/](http://localhost:12021/) 也可以使用

**Comment by louisyoungx** [comment]
最新版 [jd-shopper.exe](https://github.com/louisyoungx/jd-shopper/releases/tag/v1.2.1) 已经修复了所有问题
